{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2019-3822",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "curl",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "7.64.0"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "The curl Project"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "libcurl versions from 7.36.0 to before 7.64.0 are vulnerable to a stack-based buffer overflow. The function creating an outgoing NTLM type-3 header (`lib/vauth/ntlm.c:Curl_auth_create_ntlm_type3_message()`), generates the request HTTP header contents based on previously received data. The check that exists to prevent the local buffer from getting overflowed is implemented wrongly (using unsigned math) and as such it does not prevent the overflow from happening. This output data can grow larger than the local buffer if very large 'nt response' data is extracted from a previous NTLMv2 header provided by the malicious or broken HTTP server. Such a 'large value' needs to be around 1000 bytes or more. The actual payload data copied to the target buffer comes from the NTLMv2 type-2 response header."
            }
        ]
    },
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "7.1/CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:H",
                    "version": "3.0"
                }
            ]
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-121"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "DSA-4386",
                "refsource": "DEBIAN",
                "url": "https://www.debian.org/security/2019/dsa-4386"
            },
            {
                "name": "https://curl.haxx.se/docs/CVE-2019-3822.html",
                "refsource": "MISC",
                "url": "https://curl.haxx.se/docs/CVE-2019-3822.html"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3822",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3822"
            },
            {
                "name": "USN-3882-1",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3882-1/"
            },
            {
                "name": "106950",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/106950"
            }
        ]
    }
}